Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jcdiamante-demo-bucket-123abc
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-061dd8b45bc7deb3d
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-09200f95bef01cbf2
          GroupSet:
            - sg-090a6ffd1f91c8fde  